//
//  ReservationDetailedView.swift
//  Goodine
//
//  Created by Abhijit Saha on 27/02/25.
//

import SwiftUI
import PDFKit

struct ReservationDetailedView: View {
    
    @ObservedObject var orderVM = OrdersViewModel()
    @ObservedObject var tableVM = TableViewModel()
    
    let reservationId: String
    
    private let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        return formatter
    }()
    
    private let timeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeStyle = .short
        return formatter
    }()
    
    // Calculate total order price
    private var totalPrice: Double {
        orderVM.orders.reduce(0) { total, order in
            total + order.items.values.reduce(0) { subtotal, item in
                subtotal + (item.price * Double(item.quantity))
            }
        }
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if let reservation = tableVM.reservations.first(where: { $0.id == reservationId }) {
                
                let shortID = String(reservation.id.suffix(12))
                Text("Reservation ID: \(shortID)")
                    .font(.title2)
                    .bold()
                
                Text("Booking Date: \(reservation.timestamp, formatter: dateFormatter)")
                    .font(.subheadline)
                
                Text("Booking Time: \(reservation.timestamp, formatter: timeFormatter)")
                    .font(.subheadline)
                
                
                Divider()
                
                Text("Selected Tables & Seats")
                    .font(.headline)
                
                ForEach(reservation.tables, id: \.self) { tableNumber in
                    if let seatArray = reservation.seats[tableNumber], seatArray.contains(true) {
                        let selectedSeatCount = seatArray.filter { $0 }.count
                        HStack {
                            Text("Table \(tableNumber) - \(selectedSeatCount)")
                            Image(systemName: "person.fill")
                        }
                    }
                }
                
                Divider()
                
                Text("Ordered Items")
                    .font(.headline)
                
                if orderVM.orders.isEmpty {
                    Text("No items ordered yet.")
                        .foregroundColor(.gray)
                } else {
                    ForEach(orderVM.orders) { order in
                        VStack(alignment: .leading) {
                            ForEach(order.items.keys.sorted(), id: \.self) { key in
                                if let item = order.items[key] {
                                    Text("\(item.name) - \(item.quantity) x ₹\(item.price, specifier: "%.2f")")
                                        .font(.body)
                                }
                            }
                        }
                        .padding(.vertical, 5)
                    }
                    
                    Divider()
                    
                    // Display total price
                    HStack {
                        Text("Total Price: ")
                            .font(.headline)
                        Spacer()
                        Text("₹\(totalPrice, specifier: "%.2f")")
                            .font(.headline)
                            .foregroundColor(.mainbw)
                    }
                }
                
                Spacer()
                
                // Print Slip Button
                Button(action: {
                    generatePDF(reservation: reservation)
                }) {
                    HStack {
                        Image(systemName: "printer")
                        Text("Print Slip")
                    }
                    .goodineButtonStyle(.mainbw)
                }
                .padding(.top, 10)
            } else {
                Text("Loading reservation details...")
                    .foregroundColor(.gray)
                    .padding()
            }
        }
        .padding()
        .onAppear {
            orderVM.fetchOrders(reservationId: reservationId)
        }
    }
    
    // MARK: - Generate and Print PDF
    private func generatePDF(reservation: Reservation) {
        let pdfMetaData = [
            kCGPDFContextCreator: "Restaurant App",
            kCGPDFContextAuthor: "Generated by iOS App"
        ]
        
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        // Define receipt size (suitable for 80mm receipt printer)
        let pageWidth: CGFloat = 250 // 80mm printer width
        let pageHeight: CGFloat = 600
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight), format: format)
        
        let pdfData = renderer.pdfData { context in
            context.beginPage()
            
            let titleFont = UIFont.boldSystemFont(ofSize: 16)
            let bodyFont = UIFont.systemFont(ofSize: 12)
            let monospaceFont = UIFont(name: "Courier", size: 12) ?? bodyFont
            
            var yOffset: CGFloat = 20
            let padding: CGFloat = 10
            
            func drawText(_ text: String, font: UIFont, align: NSTextAlignment = .left, bold: Bool = false) {
                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.alignment = align
                let attributes: [NSAttributedString.Key: Any] = [
                    .font: bold ? UIFont.boldSystemFont(ofSize: font.pointSize) : font,
                    .paragraphStyle: paragraphStyle
                ]
                let attributedString = NSAttributedString(string: text, attributes: attributes)
                attributedString.draw(in: CGRect(x: padding, y: yOffset, width: pageWidth - 2 * padding, height: 20))
                yOffset += 20
            }
            
            // Print Header
            drawText("RESTAURANT ORDER SLIP", font: titleFont, align: .center, bold: true)
            drawText("Reservation ID: \(String(reservation.id.suffix(12)))", font: bodyFont)
            drawText("Date: \(dateFormatter.string(from: reservation.timestamp))", font: bodyFont)
            drawText("Time: \(timeFormatter.string(from: reservation.timestamp))", font: bodyFont)
            
            yOffset += 10
            drawText("Ordered Items", font: titleFont, bold: true)
            
            drawText("------------------------------------------------", font: monospaceFont)
            
            for order in orderVM.orders {
                for key in order.items.keys.sorted() {
                    if let item = order.items[key] {
                        let itemText = String(format: "%-15s %2d x ₹%5.2f", item.name, item.quantity, item.price)
                        drawText(itemText, font: monospaceFont)
                    }
                }
            }
            
            drawText("------------------------------------------------", font: monospaceFont)
            
            yOffset += 10
            drawText(String(format: "TOTAL: ₹%.2f", totalPrice), font: titleFont, align: .right, bold: true)
        }
        
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("OrderSlip.pdf")
        
        do {
            try pdfData.write(to: url)
            print("PDF saved at: \(url)")
            printPDF(url: url)
        } catch {
            print("Could not save PDF: \(error)")
        }
    }

    
    // MARK: - Print PDF
    private func printPDF(url: URL) {
        let printController = UIPrintInteractionController.shared
        if UIPrintInteractionController.canPrint(url) {
            let printInfo = UIPrintInfo(dictionary: nil)
            printInfo.jobName = "Order Slip"
            printInfo.outputType = .grayscale
            printController.printInfo = printInfo
            printController.showsNumberOfCopies = true
            printController.printingItem = url
            printController.present(animated: true, completionHandler: nil)
        }
    }
}

